formspree_form_id: formspree_form_id
name: André Ribas
title: André Ribas | Site
description: "André Ribas - Sites "
tags:
  - blog
  - site
  - andreribas
  - andre
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: andreribas@arnext.xyz
disqus_username: disqus_username
